### PR TITLE
add config to customize the 'create silence' page

### PR DESCRIPTION
**Pull request by br0ch0n**
This commit adds two new boolean global config values, DisableNoExpiration and
ExpireOnResolveDefault.  The intended respective usage is to hide the "No
Expiration" selection and check the "Expire on Resolve" box by default inside
the silence creation popup.

Addresses sensu/uchiwa#531 and sensu/uchiwa#538

### CODE REVIEW

**Comment by palourde** [comment]
I believe the problem with that implementation is that it's only a cosmetic change; nothing prevents a user from modifying the JS or forging a request that overrides this configuration. 

Also, I think we should move all customizations configuration attributes to a specific hash within the uchiwa hash so we separate _system_ and _user_ configurations. Any thoughts?

**Comment by br0ch0n** [comment]
Yaa, I was on the fence about moving the configs into a separate hash, but I agree it could get messy quickly especially if more get added.  Will change.
As for enforcing the expiration thing on the backend...I honestly think it's slightly overkill, but I found where to do it so I'll do it anyway :)

Patch coming...

**Comment by palourde** [comment]
Thanks for the patch!

I hope to be able to merge it before the end of the week, as soon it has been reviewed and tested.

**Comment by br0ch0n** [comment]
Thanks @palourde !  PR for corresponding docs at palourde/uchiwa-docs#10

**Comment by palourde** [comment]
Thanks so much for providing the associated documentation!

**Pull request merged**
