### PR TITLE
Added htpasswd auth support

### PR DESCRIPTION
**Pull request by n1tr0g**
- Redesigned the auth parts of the code to support additional auth mechanisms
- Support for htpasswd flat-file user database

I had to adjust the github.com/goji/httpauth to support a custom auth function. I will create a PR for that project too and in case it get merged we can switch back to the original library.

### CODE REVIEW

**Comment by palourde** [comment]
Hi @n1tr0g 

Thanks for the PR! I will be happy to merge it as soon it's added to github.com/goji/httpauth since I do not want to take the ownership of this library in case they decline the proposed change.

**Comment by n1tr0g** [comment]
Aha ok in that case I need to change the PR to remove the custom httpauth, however If they don't approve the change we are basically stuck with the limited functionality provided by this lib.

**Comment by palourde** [comment]
If they don't accept the PR then I will consider the possibility to use an another library, to allow us more flexibility.

**Comment by palourde** [comment]
I rewrote the authentication module in order to use JWT and implement a login page. Right now we offer 'simple' authentication driver, that use the configuration file, but we plan to add a text file based authentication driver as you proposed. Thanks for your PR!

**Comment by n1tr0g** [comment]
:+1:

**Comment by n1tr0g** [comment]
If I have time I will try to implement the text filed authentication. Unfortunately my PR to the previous library got refused, because I partially changed the API.

**Pull request closed without merging**
