### PR TITLE
We can have multiple users with different "role"

### PR DESCRIPTION
**Pull request by ROunofF**
Add the possibilities of having more than one user/password and even use the other flag from the Role such as readonly taken into account. I'm pretty sure this is needed in most installation where we don't want anyone to have access to silence checks, etc...

### CODE REVIEW

**Comment by palourde** [comment]
Thanks for this PR! I feel like we could simply adapt the simple auth driver to support multiple users instead, like this: https://github.com/ROunofF/uchiwa/compare/setup_multiple_users...palourde:ROunofF-setup_multiple_users. That makes sense?

**Comment by roobert** [comment]
Really looking forward to this feature.

**Comment by ROunofF** [comment]
I was wondering if I was doing that, not knowing the project I preferred to keep both ways as this would be a breaking changes for the config.json with the user/pass attributes. There's a little bit of cleanup to be done in auth.go if I'm not mistaken...

**Comment by ROunofF** [comment]
I just cleanup the unused variable and added a test for the config.GetPublic of the multiple part. I'm not 100% sure of that use but I saw you put an empty Users array there. From the look of main I don't see what it's use for so I suppose you were right and I left as is :)

Regards,

**Comment by palourde** [comment]
@ROunofF The config.GetPublic function is used to display the configuration under the *info* view. For security reasons I prefer to obfuscate all attributes related to the users.

Thanks for your PR!

**Pull request merged**
